apiVersion: v1
kind: Service
metadata:
  name: orchestrator
  namespace: deployment-orchestrator
  labels:
    app.kubernetes.io/name: orchestrator
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: orchestrator
---
apiVersion: v1
kind: Service
metadata:
  name: orchestrator-metrics
  namespace: deployment-orchestrator
  labels:
    app.kubernetes.io/name: orchestrator
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 8000
      protocol: TCP
      name: metrics
  selector:
    app.kubernetes.io/name: orchestrator
